### ISSUE TITLE
pool not communicating with node properly?

### ISSUE THREAD

**Issue by phatblinkie** [happyxie/open-moac-pool#4]
brian@moac-us:~/open-moac-pool$ ./build/bin/open-moac-pool stratum2b.json
2018/06/19 19:29:37 Loading config: /home/brian/open-moac-pool/stratum2b.json
2018/06/19 19:29:37 Running with 2 threads
2018/06/19 19:29:37 Backend check reply: PONG
2018/06/19 19:29:37 Starting API on 0.0.0.0:8080
2018/06/19 19:29:37 Set stats collect interval to 5s
2018/06/19 19:29:37 Set purge interval to 10m0s
2018/06/19 19:29:37 Purged stale stats from backend, 0 shares affected, elapsed time 255.04µs
2018/06/19 19:29:37 Stats collection finished 594.151µs
2018/06/19 19:29:37 Policy state refresh complete
2018/06/19 19:29:37 Set policy stats reset every 1h0m0s
2018/06/19 19:29:37 Set policy state refresh every 1m0s
2018/06/19 19:29:37 Running with 8 policy workers
2018/06/19 19:29:37 Upstream: main => http://127.0.0.1:8545
2018/06/19 19:29:37 Upstream: backup => http://127.0.0.2:8545
2018/06/19 19:29:37 Default upstream: main => http://127.0.0.1:8545
2018/06/19 19:29:37 Stratum listening on 0.0.0.0:8008
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Set block refresh every 120ms
2018/06/19 19:29:37 Starting proxy on 0.0.0.0:8888
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available
2018/06/19 19:29:37 Error while refreshing pending block on main: The method mc_getBlockByNumber does not exist/is not available

**Comment by happyxie** [comment]
You need install moac from https://github.com/MOACChain/moac-core/releases :
Either version 0.83 pizzaAlpha.vnode.ubuntu.tar.gz or 0.82 pangu0.8.2.ubuntu.tar.gz works.

**Comment by phatblinkie** [comment]
that is what i installed, 
 history |grep wget
   22  wget https://github.com/MOACChain/moac-core/releases/download/0.8.2/pangu0.8.2.ubuntu.tar.gz
  152  history |grep wget

**Comment by phatblinkie** [comment]
ill try pizza

**Comment by phatblinkie** [comment]
same results

**Comment by happyxie** [comment]
run moac with rpc enabled
moac --rpc

**Comment by phatblinkie** [comment]
so i had a big write up, but here is what i found
fails = ./moac  --rpc --rpcaddr "127.0.0.1" --rpcport "8545" --rpcapi "eth,net,web3"
works = ./moac  --rpc --rpcaddr "127.0.0.1" --rpcport "8545"

maybe a bug on the node more than the pool.
